import mongoose from 'mongoose';

/**
 * Transcript Schema
 * 
 * Represents the transcription of a lecture audio file.
 * Contains the full text and segmented transcript with timestamps.
 * Generated by Azure Speech-to-Text API.
 */
const transcriptSegmentSchema = new mongoose.Schema({
  start: {
    type: Number,
    required: true // Start time in seconds
  },
  end: {
    type: Number,
    required: true // End time in seconds
  },
  text: {
    type: String,
    required: true
  }
}, { _id: false });

const transcriptSchema = new mongoose.Schema({
  lectureId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Lecture',
    required: true,
    unique: true // One transcript per lecture
  },
  text: {
    type: String,
    required: true
  },
  segments: [transcriptSegmentSchema]
}, {
  timestamps: true // Adds createdAt and updatedAt automatically
});

export default mongoose.model('Transcript', transcriptSchema);

